import { StatList } from "./list"

export const stat = StatList(
    // No stat
    "NONE",

    "SHIELDED",

    // ATK

    "ATK",
    "ATK_BASE",
    "ATK_PERCENT",
    "ATK_FLAT",

    // HP

    "HP_CURRENT",
    "HP",
    "HP_BASE",
    "HP_PERCENT",
    "HP_FLAT",

    // DEF

    "DEF",
    "DEF_BASE",
    "DEF_PERCENT",
    "DEF_FLAT",

    // ADVANCED
    "ENERGY_CURRENT",
    "ELEMENTAL_MASTERY",
    "ENERGY_RECHARGE",
    "HEALING_BONUS",
    "CRIT_RATE",
    "EXTRA_CRIT_RATE",
    "CRIT_DMG",
    "ALL_DMG",
    "DEFIGNORED",
    "DEFREDUCTION",

    "DMG_FLAT",

    // ELEMENTAL DMG

    "PYRO_DMG",
    "CRYO_DMG",
    "HYDRO_DMG",
    "ELECTRO_DMG",
    "ANEMO_DMG",
    "GEO_DMG",
    "DENDRO_DMG",
    "PHYSICAL_DMG",

    "PYRO_DMG_FLAT",
    "CRYO_DMG_FLAT",
    "HYDRO_DMG_FLAT",
    "ELECTRO_DMG_FLAT",
    "ANEMO_DMG_FLAT",
    "GEO_DMG_FLAT",
    "DENDRO_DMG_FLAT",
    "PHYSICAL_DMG_FLAT",

    // REACTION DMG

    "MELT_DMG",
    "VAPORIZE_DMG",
    "SWIRL_DMG",
    "OVERLOAD_DMG",
    "ELECTROCHARGE_DMG",
    "SUPERCONDUCT_DMG",
    "SHATTER_DMG",
    "AGGRAVATE_DMG",
    "SPREAD_DMG",
    "BLOOM_DMG",
    "HYPERBLOOM_DMG",
    "BURGEON_DMG",
    "BURNING_DMG",

    // TALENT DMG

    "NORMAL_ATTACK_DMG",
    "CHARGED_ATTACK_DMG",
    "AIMED_SHOT_DMG",
    "CHARGED_AIMED_SHOT_DMG",
    "PLUNGE_ATTACK_DMG",
    "ELEMENTAL_SKILL_DMG",
    "ELEMENTAL_BURST_DMG",

    "NORMAL_ATTACK_DMG_FLAT",
    "CHARGED_ATTACK_DMG_FLAT",
    "AIMED_SHOT_DMG_FLAT",
    "CHARGED_AIMED_SHOT_DMG_FLAT",
    "PLUNGE_ATTACK_DMG_FLAT",
    "ELEMENTAL_SKILL_DMG_FLAT",
    "ELEMENTAL_BURST_DMG_FLAT",

    // TALENT LEVELS

    "NORMAL_ATTACK_LEVEL",
    "ELEMENTAL_SKILL_LEVEL",
    "ELEMENTAL_BURST_LEVEL",
    "NORMAL_ATTACK_LEVEL_UP",
    "ELEMENTAL_SKILL_LEVEL_UP",
    "ELEMENTAL_BURST_LEVEL_UP",

    // TALENT ATK%

    "NORMAL_ATTACK_ATK_PERCENT",
    "CHARGED_ATTACK_ATK_PERCENT",
    "PLUNGE_ATTACK_ATK_PERCENT",
    "AIMED_SHOT_ATK_PERCENT",
    "CHARGED_AIMED_SHOT_ATK_PERCENT",
    "ELEMENTAL_SKILL_ATK_PERCENT",
    "ELEMENTAL_BURST_ATK_PERCENT",

    // ELEMENTAL ATK%

    "PYRO_ATK_PERCENT",
    "CRYO_ATK_PERCENT",
    "ELECTRO_ATK_PERCENT",
    "HYDRO_ATK_PERCENT",
    "GEO_ATK_PERCENT",
    "ANEMO_ATK_PERCENT",
    "DENDRO_ATK_PERCENT",
    "PHYSICAL_ATK_PERCENT",

    // TALENT ATK FLAT

    "NORMAL_ATTACK_ATK_FLAT",
    "CHARGED_ATTACK_ATK_FLAT",
    "PLUNGE_ATTACK_ATK_FLAT",
    "AIMED_SHOT_ATK_FLAT",
    "CHARGED_AIMED_SHOT_ATK_FLAT",
    "ELEMENTAL_SKILL_ATK_FLAT",
    "ELEMENTAL_BURST_ATK_FLAT",
    // ELEMENTAL ATK FLAT
    "PYRO_ATK_FLAT",
    "CRYO_ATK_FLAT",
    "ELECTRO_ATK_FLAT",
    "HYDRO_ATK_FLAT",
    "GEO_ATK_FLAT",
    "ANEMO_ATK_FLAT",
    "DENDRO_ATK_FLAT",
    "PHYSICAL_ATK_FLAT",

    // TALENT CRIT RATE

    "NORMAL_ATTACK_CRIT_RATE",
    "CHARGED_ATTACK_CRIT_RATE",
    "PLUNGE_ATTACK_CRIT_RATE",
    "AIMED_SHOT_CRIT_RATE",
    "CHARGED_AIMED_SHOT_CRIT_RATE",
    "ELEMENTAL_SKILL_CRIT_RATE",
    "ELEMENTAL_BURST_CRIT_RATE",

    // ELEMENTAL CRIT RATE

    "PYRO_CRIT_RATE",
    "CRYO_CRIT_RATE",
    "ELECTRO_CRIT_RATE",
    "HYDRO_CRIT_RATE",
    "GEO_CRIT_RATE",
    "ANEMO_CRIT_RATE",
    "DENDRO_CRIT_RATE",
    "PHYSICAL_CRIT_RATE",

    // TALENT CRIT DMG

    "NORMAL_ATTACK_CRIT_DMG",
    "CHARGED_ATTACK_CRIT_DMG",
    "PLUNGE_ATTACK_CRIT_DMG",
    "AIMED_SHOT_CRIT_DMG",
    "CHARGED_AIMED_SHOT_CRIT_DMG",
    "ELEMENTAL_SKILL_CRIT_DMG",
    "ELEMENTAL_BURST_CRIT_DMG",

    // ELEMENTAL CRIT DMG

    "PYRO_CRIT_DMG",
    "CRYO_CRIT_DMG",
    "ELECTRO_CRIT_DMG",
    "HYDRO_CRIT_DMG",
    "GEO_CRIT_DMG",
    "ANEMO_CRIT_DMG",
    "DENDRO_CRIT_DMG",
    "PHYSICAL_CRIT_DMG",

    // ENTITY STATS

    "LEVEL",
    "ASCENSION",

    // ELEMENTAL RES

    "PYRO_RES",
    "CRYO_RES",
    "ELECTRO_RES",
    "HYDRO_RES",
    "GEO_RES",
    "ANEMO_RES",
    "DENDRO_RES",
    "PHYSICAL_RES",

)